apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpu-operator
spec:
  template:
    spec:
      containers:
      - name: manager
        args:
        - --config=/controller_manager_config.yaml
        - --zap-log-level=2
        volumeMounts:
        - name: kpu-operator-config
          mountPath: /controller_manager_config.yaml
          subPath: config.yaml
          readOnly: true
      volumes:
      - name: kpu-operator-config
        configMap:
          name: kpu-operator-config
