apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# https://github.com/projectcontour/contour/tree/release-1.33/examples/gateway-provisioner

resources:
  - 00-crds.yaml
  - 01-common.yaml
  - 02-roles.yaml
  - 03-rolebindings.yaml
  - 04-gateway-provisioner.yaml
